Solicitud devolucion4 resumen
udistrital/central_cuentas_cliente pull request #105
Opened 2021-01-07 00:03 UTC by Jeisson005

Issue 91

2021-01-08 00:22 UTC, BOTOOM requested changes

2021-01-08 00:22 UTC, BOTOOM commented on src/app/pages/solicitud-devolucion/components/set-anexosimpuestos/set-anexosimpuestos.component.ts
> -    this.datosAnexos = DATOS_TABLA_ANEXOS;
aqui eliminaste el uso de `DATOS_TABLA_ANEXOS` por ende la interfaz que tenia esos datos no se deberia estar usando, si es el caso porfa borrala, en caso contrario informarme

2021-01-08 03:38 UTC, Jeisson005 commented on src/app/pages/solicitud-devolucion/components/set-anexosimpuestos/set-anexosimpuestos.component.ts
> -    this.datosAnexos = DATOS_TABLA_ANEXOS;
Es correcto, ya no se usa, por lo que la borro del archivo _interfaces.ts_ y de las importaciones

2021-01-13 00:53 UTC, BOTOOM approved these changes

2021-01-13 00:53 UTC, merged