Feature/soliditudgiros/consultasapi
udistrital/central_cuentas_cliente pull request #106
Opened 2021-01-07 17:17 UTC by dmarcela09

Se consultan los endpoints del api de Terceros, se realiza dentro del modulo "Shared" y se implementa en el modulo de "Solicitud de Autorizacion de Giro":

Tipos de ID (Para issue #93 )
![1](https://user-images.githubusercontent.com/26507343/103922385-aa4d7a00-50e1-11eb-91e4-eaf53b3898d4.png)

En el modulo se requieren de mas de una consulta para el "Solicitante" y "Beneficiario", se ajusta para el caso:
Datos de Identificacion (Para issue #95 )
![imagen](https://user-images.githubusercontent.com/26507343/103922701-1e881d80-50e2-11eb-8963-677c7afdb0ff.png)

2021-01-13 03:34 UTC, BOTOOM requested changes

2021-01-13 03:34 UTC, BOTOOM commented on src/app/pages/solicitudesgiros/components/set-autorizaciongiro/set-autorizaciongiro.component.html
> +                    <option [ngValue]="tipoId" *ngFor="let tipoId of tiposID">{{ tipoId.CodigoAbreviacion }}</option>
ya que el select es grande es mejor que muestres el nombre ya que no todas las abreviaciones son fáciles de identificar

2021-01-13 03:34 UTC, BOTOOM commented on src/app/shared/effects/shared.effects.ts
> +                    TerceroId: {
Hubiera quedado mas facil y con menos código hacer : `TerceroId : tercero.TerceroId` y ya de una te mapea todo son necesidad de tener que pasar por cada atributo.

porfa ajustalo :smile:

2021-01-13 03:34 UTC, BOTOOM commented on src/app/shared/services/shared.service.ts
> +    return this.rqManager.get('tipo_documento');
con el fin de reducir el peso de la petición aunque la petición es liviana pero es e mejor reducir el peso, solo trae los campos necesarios, en otro comentario te mencione que usaras el nombre para mostrar en el select, asi que porfa en la peticion solo trae el nombre y el id.

adicionalmente debes de solo traer los que tengan el campo activo true, con el fin de evitar datos dommie que en algún momento llegue a añadir

2021-01-14 00:42 UTC, dmarcela09 commented on src/app/pages/solicitudesgiros/components/set-autorizaciongiro/set-autorizaciongiro.component.html
> +                    <option [ngValue]="tipoId" *ngFor="let tipoId of tiposID">{{ tipoId.CodigoAbreviacion }}</option>
En el nuevo commit se cambia el dato: de codigo de abreviacion a nombre para claridad del usuario

2021-01-14 00:43 UTC, dmarcela09 commented on src/app/shared/effects/shared.effects.ts
> +                    TerceroId: {
Se realiza el cambio en el ultimo commit

2021-01-14 02:33 UTC, BOTOOM approved these changes

2021-01-14 02:34 UTC, merged