Autorizacion solicitud de giro
udistrital/central_cuentas_cliente pull request #147
Opened 2022-03-03 04:13 UTC by diagutierrezro

#141

2022-03-03 04:29 UTC, diagutierrezro commented
Se debe desplegar el crud en ambiente de pruebas antes para actualizar las variables de entorno

2022-03-03 06:03 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/effects/solicitudesgiros.effects.ts
> +            SolicitudesGiro: ((data && data.Data) ? data.Data : data)});
Tratar que esta lógica del desencapsulamiento quede dentro del service, para que el uso del service sea transparente...
Esto quizás también tenga que ver con lo comentado en `src/app/@core/managers/requestManager.ts`...

2022-03-24 17:32 UTC, diagutierrezro commented on src/app/@core/managers/requestManager.ts
>    }
Realicé diferentes pruebas con el crud y las respuestas del crud se están generando de manera correcta por lo que no considero que sea necesario agregarle la otra condición

2022-03-24 17:38 UTC, diagutierrezro commented on src/environments/environment.ts
>  export const environment = {
Esto aun no se realiza debido a que no se ha realizado el despliegue completo, una vez se tengan bien las variables de entorno se modificarán

2022-03-24 17:39 UTC, diagutierrezro commented on src/app/pages/solicitudesgiros/components/set-infosolicitudgiro/set-infosolicitudgiro.component.ts
> +    this.info_token = (JSON.parse(atob(localStorage.getItem('id_token').split('.')[1])));
Se crea el servicio similar al de arka

2022-03-24 21:41 UTC, AlexFBP reviewed
- Hay algunas partes en que se repetiría código, revisar...
- Respecto a i18n, no concatenar variables/frases, usar la interpolacion de variables para ello
- Eliminar codigo comentado o indicar (tambien en comentarios) por qué se deja comentado

Se recomienda ver los comentarios desde "Files Changed" para tener un mejor contexto/vista de cada comentario

2022-03-24 21:41 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/components/table-listasolicitudes/table-listasolicitudes.component.html
> +        </mat-form-field> -->
... No agregar más código comentado :joy: 
O al menos dejar comentado (también en código) por qué el bloque está comentado, para referencias futuras

2022-03-24 21:41 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/components/table-listasolicitudes/table-listasolicitudes.component.ts
> +    }
En general/En lo posible, [evitar los for](https://blog.sapegin.me/all/avoid-loops/) y usar métodos de array
```suggestion
    const tableArr: Element[] = this.solicitudesGiro.map(solicitud => { return <Element>{
      NumeroSolicitud: solicitud.Numero_Solicitud,
      NombreBeneficiario: solicitud.Nombre_Beneficiario,
      Fecha: this.datePipe.transform(solicitud.Fecha_creacion, 'dd-MM-yyyy'),
      Estado: solicitud.Estado,
      estado: true,
      Id: solicitud._id,
      acciones: '',
    }});
```

2022-03-24 21:41 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/effects/solicitudesgiros.effects.ts
> +            SolicitudesGiro: ((data && data.Data) ? data.Data : data)});
En otras palabras, no debería importar si los datos vienen encapsulados ni si el encapsulamiento viene por `Data` o por `Body`

2022-03-24 21:41 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/effects/solicitudesgiros.effects.ts
> +          this.popupManager.showSuccessAlert(this.translate.instant('CUENTA_BANCARIA.guardado_exitoso con el consecutivo ' + accion.element.Numero_Solicitud)).then((result) => {
Debe especificarse únicamente la key i18n, y aplicar interpolación de variables cuando las hayan. Digamos, si en json i18n se dejara algo así:
```json
{
  "CUENTA_BANCARIA": {
    "guardado_exitoso": "Se guardó exitosamente con consecutivo {{CONSECUTIVO}}"
  }
}
```
entonces el texto se podría traer con
```typescript
this.translate.instant('CUENTA_BANCARIA.guardado_exitoso', {CONSECUTIVO: accion.element.Numero_Solicitud})
```
El método `instant` acepta un segundo parámetro que es un objeto con las variables a interpolar

Lo anterior dado que cada localización (lengua/idioma) tiene sus normas, y si se parte la frase, se pierde el contexto de la localización/traducción...

2022-03-24 21:41 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/effects/solicitudesgiros.effects.ts
> +                this.popupManager.showSuccessAlert(this.translate.instant('CUENTA_BANCARIA.guardado_exitoso')).then((result) => {
Revisar junto a lo comentado en la L39

2022-03-24 21:41 UTC, AlexFBP commented on src/app/shared/services/shared.service.ts
> +    return this.rqManager.get(`arbol_rubro/arbol/3`, params);
Este `3` es el mismo de la L71 de `src/app/shared/components/arbol-rubro/arbol-rubro.component.ts` ?
De ser así, hacer que venga de un mismo lado, de una misma constante (y ajustar también el archivo mencionado)

2022-03-25 16:51 UTC, diagutierrezro commented on src/app/shared/services/shared.service.ts
> +    return this.rqManager.get(`arbol_rubro/arbol/3`, params);
Se dejó el servicio como estaba antes, había quemado el 3 para hacer pruebas y se me pasó volverlo a modificar, quedó unicamente en el componente

2022-03-25 18:04 UTC, diagutierrezro commented on src/app/pages/solicitudesgiros/effects/solicitudesgiros.effects.ts
> +            SolicitudesGiro: ((data && data.Data) ? data.Data : data)});
Se realizó la modificación en los tres servicios de las solicitudes (post, put y get all)

2022-03-26 06:13 UTC, AlexFBP requested changes
En general, bien
Algunos ajustes menores y quedaría

2022-03-26 06:13 UTC, AlexFBP commented on src/environments/environment.test.ts
>    KNOWAGE: {
- Faltaría actualizar también el environment.prod.ts
- Si ya se está usando el gestor documental, revisar de paso si de una vez se puede quitar este bloque, `KNOWAGE: {...}`

2022-03-26 06:13 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/components/set-cargardocumentos/set-cargardocumentos.component.html
>  <!-- Fin Modal -->
```suggestion
<!-- Fin Modal -->

```

2022-03-26 06:13 UTC, AlexFBP commented on src/app/pages/solicitudesgiros/components/set-autorizaciongiro/set-autorizaciongiro.component.ts
> +    this.acciones_disabled = ACCIONES_DISABLED;
(En general, al importar constantes, y tomando estas como ejemplo)
Si `acciones_edi` ni `acciones_disabled` se van a usar, se podrían ahorrar/evitar estas variables intermedias y usar directamente `ACCIONES_EDI` y `ACCIONES_DISABLED`
(No es estrictamente necesario aplicar este comentario)

2022-03-28 05:13 UTC, diagutierrezro commented on src/environments/environment.test.ts
>    KNOWAGE: {
Se elimina el knowage, realicé pruebas cargando archivos sin estas variables y funciona correctamente

2022-03-28 19:21 UTC, AlexFBP requested changes
Un cambio menor y quedaría

2022-03-28 19:21 UTC, AlexFBP commented on src/environments/environment.ts
> -    },
Replicar esta eliminación de `NUXEO: {...}` en los otros dos archivos (test/prod)

2022-03-28 19:37 UTC, AlexFBP approved these changes

2022-03-28 20:07 UTC, merged

2022-03-28 20:08 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/central_cuentas_cliente/277)