Adición del endoso a la orden de pago
udistrital/central_cuentas_cliente pull request #161
Opened 2022-04-21 06:58 UTC by diagutierrezro

#145

2022-04-21 07:31 UTC, AlexFBP reviewed
Revisión inicial bajo comentarios mientras se quita el estado Draft / borrador

2022-04-21 07:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-movimientocontable/set-movimientocontable.component.ts
> +                      cuentaCredito: (this.cuentasContablesConcepto[this.cuentasContablesConcepto.findIndex((e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto)]),
Linea larga, una posible forma de partirla por legibilidad sería esta:
```suggestion
                      cuentaCredito: (this.cuentasContablesConcepto[
                        this.cuentasContablesConcepto
                          .findIndex((e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto)
                        ]),
```

Por otro lado, por qué no usar no mas...?
```suggestion
                      cuentaCredito: this.cuentasContablesConcepto
                        .find((e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto),
```

2022-04-21 07:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-movimientocontable/set-movimientocontable.component.ts
>                    this.boolean = true;
Renombrar esta variable, en vez de `boolean` algo más descriptivo... `conceptosCompletos` quizás?

2022-04-21 07:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-movimientocontable/set-movimientocontable.component.ts
> +                      cuentaCredito: (this.cuentasContablesConcepto[this.cuentasContablesConcepto.findIndex((e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto)]),
Linea muy larga... Dividirla por legibilidad. Una forma podría ser esta:
```suggestion
                      cuentaCredito: (this.cuentasContablesConcepto[
                        this.cuentasContablesConcepto.findIndex(
                          (e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto
                        )
                      ]),
```

Por otro lado, por qué no usar no mas ... ?
```suggestion
                      cuentaCredito: this.cuentasContablesConcepto
                        .find((e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto),
```

2022-04-21 08:08 UTC, diagutierrezro commented on src/app/pages/ordenesdepago/components/set-movimientocontable/set-movimientocontable.component.ts
> +                      cuentaCredito: (this.cuentasContablesConcepto[this.cuentasContablesConcepto.findIndex((e: any) => e.cuenta.Codigo === this.ordenPago.CuentaValorNeto)]),
:)

2022-04-21 21:35 UTC, AlexFBP requested changes

2022-04-21 21:35 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-impuestosyretenciones/set-impuestosyretenciones.component.ts
> +      });
Código duplicado con las L133-135, moverlo a una `private function` de esta `class`

2022-04-21 21:35 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-movimientocontable/set-movimientocontable.component.ts
> +        }
Se podría simplificar...
```suggestion
      if (nodoCuenta && Object.keys(nodoCuenta)[0] !== 'type' && !nodoCuenta.children) {
        this.SeleccionarCuentaContable(nodoCuenta);
        this.cuentaContableSeleccionada1 = nodoCuenta.data;
        nodoCuenta = null;
        this.movimientoContable.patchValue({
          cuentaContableEndoso: this.cuentaContableSeleccionada1
        });
```

2022-04-21 21:35 UTC, AlexFBP commented on src/app/pages/ordenesdepago/effects/ordenespago.effects.ts
> +        this.popupManager.showSuccessAlert(this.translate.instant('ORDEN_PAGO.guardado_exitoso', {CONSECUTIVO: accion.element.Consecutivo})).then((result) => {
```suggestion
        this.popupManager
        .showSuccessAlert(this.translate.instant('ORDEN_PAGO.guardado_exitoso',
          {CONSECUTIVO: accion.element.Consecutivo}))
        .then((result) => {
```

2022-04-21 21:35 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-impuntuacionpresupuestal/set-impuntuacionpresupuestal.component.html
> +        <small *ngIf="datosTableImputacion == 0" class="text-danger">{{ 'GLOBAL.tabla_no_vacia' | translate}}</small>
```suggestion
        <small *ngIf="datosTableImputacion === 0" class="text-danger">{{ 'GLOBAL.tabla_no_vacia' | translate}}</small>
```

2022-04-21 21:35 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/set-impuestosyretenciones/set-impuestosyretenciones.component.html
> +        <small *ngIf="datosTableImpuestosRetenciones == 0" class="text-danger">{{ 'GLOBAL.tabla_no_vacia' | translate}}</small>
```suggestion
        <small *ngIf="datosTableImpuestosRetenciones === 0" class="text-danger">{{ 'GLOBAL.tabla_no_vacia' | translate}}</small>
```

2022-04-23 03:30 UTC, AlexFBP approved these changes

2022-04-23 03:30 UTC, merged