Flujo de aprobacion de ordenes de pago
udistrital/central_cuentas_cliente pull request #165
Opened 2022-05-04 04:52 UTC by diagutierrezro

#145

2022-05-04 16:31 UTC, AlexFBP requested changes

2022-05-04 16:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/show-resumenordenpago/show-resumenordenpago.component.ts
> +      text: '¿Seguro que deseas aprobar esta orden de pago?',
Traer de i18n

2022-05-04 16:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/show-resumenordenpago/show-resumenordenpago.component.ts
> +      confirmButtonText: 'Si, aprobar'
Traer de i18n

2022-05-04 16:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/show-resumenordenpago/show-resumenordenpago.component.ts
> +            elemento.Estado = 'Firmado';
Respecto a todos los usos de `elemento.Estado`, ver lo comentado en la L196

2022-05-04 16:31 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/show-resumenordenpago/show-resumenordenpago.component.ts
> +      confirmButtonText: 'Si, rechazar'
Traer mediante i18n

2022-05-05 17:45 UTC, AlexFBP requested changes
En general, bien. Algunos comentarios finales a revisar

2022-05-05 17:45 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/table-listaordenes/table-listaordenes.component.ts
> +    element.Estado = 'Por revisar contabilidad';
De manera similar a lo comentado [anteriormente](https://github.com/udistrital/central_cuentas_cliente/pull/165#discussion_r865025950) para `src/app/pages/ordenesdepago/components/show-resumenordenpago/show-resumenordenpago.component.ts`:

1. Este string no está destinado a ser mostrado en la interfaz sino principalmente para la lógica, si?
2. De ser así (un string solo para la lógica), traerlo de una constante o de un [`enum` de `string`s](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) para los posibles estados que se pueda aprovechar en varios lados - NOTA: Si se trata de los mismos estados, se puede `export`ar el `enum Aprobacion` de `src/app/pages/ordenesdepago/components/show-resumenordenpago/show-resumenordenpago.component.ts` (o moverlo a otro archivo y también `export`arlo de allá)

2022-05-05 17:45 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/table-listaordenes/table-listaordenes.component.ts
> +    const ACCIONES_EDICION: string[] = ['Por revisar contabilidad', 'Por revisar presupuesto', 'Por revisar tesoreria', 'Aprobado'];
Ver comentario en la L94 respecto a los estados

2022-05-05 17:45 UTC, AlexFBP commented on src/app/pages/ordenesdepago/components/table-listaordenes/table-listaordenes.component.html
> +                    <mat-icon title="Enviar" *ngIf="column.title.name==='acciones' && (element.Estado==='Elaborado')" (click)="enviarRevision(element)">send</mat-icon>
Continuando [lo anteriomente comentado](https://github.com/udistrital/central_cuentas_cliente/pull/165#discussion_r865032509), el siguiente paso sería:
- En el .ts, declarar variables a ser usadas en los `ngIf` del .html, cuyo valor se actualizaría en cualquier evento que implique una actualización en `column.title.name`  o en `element.Estado`:
  ```typescript
  class ... {
    mostrarEditar: boolean;
    mostrarRevisar: boolean;
    // ...

    // Evento inventado, de ejemplo; lo que importa es llamar a refrescarBotones()
    // donde quiera que implique un cambio en `this.element.Estado`
    onEstadoChange() {
      this.refrescarBotones();
    }

    // Evento inventado, de ejemplo; lo que importa es llamar a refrescarBotones()
    // donde quiera que implique un cambio en `this.column.title.name`
    onColumnaChange() {
      this.refrescarBotones();
    }

    private refrescarBotones() {
      this.mostrarEditar = this.column.title.name==='acciones' && this.edicion(element.Estado)
      this.mostrarRevisar = this.column.title.name==='acciones' && this.edicion(element.Estado)
    }
    // ...
  }
  ```
- Desde el html, en los `ngIf`, usar las variables anteriormente creadas
  ```html
  <mat-icon title="Editar" *ngIf="mostrarEditar">...</mat-icon>
  ```

2022-05-07 00:25 UTC, diagutierrezro commented on src/app/pages/ordenesdepago/components/table-listaordenes/table-listaordenes.component.html
> +                    <mat-icon title="Enviar" *ngIf="column.title.name==='acciones' && (element.Estado==='Elaborado')" (click)="enviarRevision(element)">send</mat-icon>
Lo manejé de una manera un poco diferente ya que el "element" no se maneja directamente en el .ts, este se usar en el html tomandolo del arreglo de datos que se pasan por el MatTable, lo que hice fue crear dos variables solo para manejar la logica donde voy a calcular directamente si se puede editar o revisar y envío esta información dentro del json que mando a la tabla

2022-05-07 00:25 UTC, diagutierrezro commented on src/app/pages/ordenesdepago/components/table-listaordenes/table-listaordenes.component.html
> +                    <mat-icon title="Enviar" *ngIf="column.title.name==='acciones' && (element.Estado==='Elaborado')" (click)="enviarRevision(element)">send</mat-icon>
Lo manejé de una manera un poco diferente ya que el "element" no se maneja directamente en el .ts, este se usar en el html tomandolo del arreglo de datos que se pasan por el MatTable, lo que hice fue crear dos variables solo para manejar la logica donde voy a calcular directamente si se puede editar o revisar y envío esta información dentro del json que mando a la tabla

2022-05-10 02:40 UTC, AlexFBP approved these changes
Aprobado con comentarios: quizás falten algunas validaciones? (Dejadas como _suggested changes_)

2022-05-10 03:04 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/central_cuentas_cliente/332)

2022-05-10 03:04 UTC, merged