Creación de devoluciones tributarias
udistrital/central_cuentas_cliente pull request #168
Opened 2022-05-24 02:06 UTC by diagutierrezro

#167

2022-05-24 05:42 UTC, AlexFBP requested changes
En general, bien. Varios de los comentarios dejados son de _suggested changes_ menores

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +    this.subscriptionContabilizacion$ = this.store.select(getContabilizacion).subscribe((action) => {
```suggestion
    this.subscriptionContabilizacion$ = this.store
    .select(getContabilizacion).subscribe((action) => {
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +    this.subscriptionInfoDevolucionTributaria$ = this.store.select(getInfoDevolucionTributaria).subscribe((action) => {
```suggestion
    this.subscriptionInfoDevolucionTributaria$ = this.store
    .select(getInfoDevolucionTributaria).subscribe((action) => {
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +    this.subscriptionDatosOP$ = this.store.select(getDatosOrdenesPago).subscribe((action) => {
```suggestion
    this.subscriptionDatosOP$ = this.store
    .select(getDatosOrdenesPago).subscribe((action) => {
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +    this.subscriptionDatosContabilizacion$ = this.store.select(getDatosContabilizacion).subscribe((action) => {
```suggestion
    this.subscriptionDatosContabilizacion$ = this.store
    .select(getDatosContabilizacion).subscribe((action) => {
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +      this.store.dispatch(crearDevolucionTributaria({element: elemento}));
```suggestion
    this.store.dispatch(crearDevolucionTributaria({element: elemento}));
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +      });
```suggestion
      return Object.values( this.comprobantepagoGroup.controls )
      .forEach( control => { control.markAsTouched(); } );
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/table-devoluciontributaria/table-devoluciontributaria.component.html
> +                <th mat-header-cell *matHeaderCellDef> {{column.title.name}}</th>
```suggestion
                <th mat-header-cell *matHeaderCellDef>{{column.title.name}}</th>
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/table-devoluciontributaria/table-devoluciontributaria.component.ts
> +];
Considerar exportar estos estados y/o moverlos a un archivo en caso que sean comunes a otros componentes

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/devoluciontributaria.module.ts
> +    {provide: MAT_DATE_LOCALE, useValue: 'fr'},
1. Ver lo comentado en la L41 de `src/app/pages/devoluciontributaria/components/set-infodevoluciontributaria/set-infodevoluciontributaria.component.ts`
2. En caso de persistir, "factorizar" el `'fr'`, moverlo a un único lado del código, a una constante del sistema

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/effects/devoluciontributaria.effects.ts
> +      pipe(map(data => {
```suggestion
      mergeMap((accion) => this.servicio
      .crearDevolucionTributaria(accion.element)
      .pipe(map(data => {
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/interfaces/interfaces.ts
> +                name: 'Consecutivo',
(En general para este archivo) Traer los name y otros campos destinados a interfaz, mediante i18n. Una forma de hacerlo podría ser como en los 2 primeros archivos cambiados por el commit https://github.com/udistrital/plan_adquisiciones_cliente/commit/8dd46f8c890295426a6dc65f6bafe154cf3e5d3c

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/interfaces/interfaces.ts
> +                name: 'Consecutivo',
(en general para este archivo y otros casos similares) Traer los `name` y otros destinados a interfaz, mediante i18n. Una forma de hacerlo podría ser como en los cambios a los dos primeros archivos del siguiente commit 
https://github.com/udistrital/plan_adquisiciones_cliente/commit/8dd46f8c890295426a6dc65f6bafe154cf3e5d3c

2022-05-24 05:42 UTC, AlexFBP commented on src/app/shared/services/shared.service.ts
> +        return this.rqManager.getv2(`orden-pago/?query=DocumentoBeneficiario:${doc},Estado:Firmado`, null, null, null, null, null, 0);
Ajustar el `rqManager.getv2` para que los parametros no especificados tomen los `null` y el `0`, prácticamente en el mismo orden que aparecen acá
De tal manera que acá se pueda hacer lo siguiente y no pase nada
```suggestion
        return this.rqManager.getv2(`orden-pago/?query=DocumentoBeneficiario:${doc},Estado:Firmado`);
```

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/table-devoluciontributaria/table-devoluciontributaria.component.scss
> +}
las dos propiedades `border-*` son comunes a las tres primeras clases anteriores. Crear y usar una nueva clase con estas dos propiedades y quitarlas, "factorizarlas". Si esta nueva clase podría usarse en otro(s) componente(s), se recomienda moverla a un CSS mas general

2022-05-24 05:42 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/devoluciontributaria.module.ts
> +    {provide: MAT_DATE_LOCALE, useValue: 'fr'},
1. Ver lo comentado en la L41 de `src/app/pages/devoluciontributaria/components/set-infodevoluciontributaria/set-infodevoluciontributaria.component.ts`
2. En caso de proceder, buscar la manera de traer el `'fr'` de un mismo lado en todo el código, a modo de una "constante del sistema"

2022-05-24 07:47 UTC, diagutierrezro reviewed
Realicé los cambios referentes al isInvalid, sin embargo me queda la duda de que es mejor ya que con el otro metodo hay que declarar muchas mas variables y considero que el codigo se extiende innecesariamente

2022-05-28 17:36 UTC, AlexFBP approved these changes
Aprobado con comentarios

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.html
> +<div class="cotainer">
Revisar: Quizás ... ?
```suggestion
<div class="container">
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +    ) {
```suggestion
  ) {
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +   }
```suggestion
  }
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.ts
> +  }
```suggestion
  }

```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/table-devoluciontributaria/table-devoluciontributaria.component.ts
> +      this.configuracion.dataConfig[i].title.name = this.translate.instant('DEVOL_TRIBUTARIA.' + this.configuracion.dataConfig[i].title.label_i18n);
```suggestion
      this.configuracion.dataConfig[i].title.name = this.translate
        .instant('DEVOL_TRIBUTARIA.' + this.configuracion.dataConfig[i].title.label_i18n);
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/shared/components/general-table/general-table.component.html
> +                                        {{ config.secuencia.pipe.type ? (items[config.secuencia.key] | multiPipe:config.secuencia.pipe.type:config.secuencia.pipe.config) : items[config.secuencia.key]
De ser posible
```suggestion
                                    {{ config.secuencia.pipe.type
                                           ? (items[config.secuencia.key] | multiPipe:config.secuencia.pipe.type:config.secuencia.pipe.config)
                                           : items[config.secuencia.key] }}
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/shared/services/shared.service.ts
> +        return this.rqManager.getv2(`orden-pago/?query=DocumentoBeneficiario:${doc},Estado:Firmado`);
Validar si funciona igual
```suggestion
        return this.rqManager.getv2(`orden-pago?query=DocumentoBeneficiario:${doc},Estado:Firmado`);
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/set-contabilizacion/set-contabilizacion.component.ts
> +      ) {
```suggestion
    private activatedRoute: ActivatedRoute,
  ) {
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/set-contabilizacion/set-contabilizacion.component.ts
> +          this.configContabilizacion.dataConfig[i].title.name = this.translate.instant('DEVOL_TRIBUTARIA.' + this.configContabilizacion.dataConfig[i].title.label_i18n);
```suggestion
          this.configContabilizacion.dataConfig[i].title.name = this.translate
            .instant('DEVOL_TRIBUTARIA.' + this.configContabilizacion.dataConfig[i].title.label_i18n);
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/set-contabilizacion/set-contabilizacion.component.ts
> +      }
```suggestion
  }
```

2022-05-28 17:36 UTC, AlexFBP commented on src/app/pages/devoluciontributaria/components/set-contabilizacion/set-contabilizacion.component.ts
> +   private mostrar(action: string): boolean {
```suggestion
  private mostrar(action: string): boolean {
```

2022-05-28 17:46 UTC, diagutierrezro commented on src/app/pages/devoluciontributaria/components/show-resumendevolucion/show-resumendevoluciontributaria.component.html
> +<div class="cotainer">
xd

2022-05-28 18:17 UTC, AlexFBP approved these changes

2022-05-30 23:48 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/central_cuentas_cliente/342)

2022-05-30 23:48 UTC, merged