Ordenes de devolución
udistrital/central_cuentas_cliente pull request #170
Opened 2022-06-01 21:56 UTC by diagutierrezro

#167

2022-06-05 04:49 UTC, AlexFBP reviewed
Revisión preliminar

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                    Datos del Beneficiario
Traer de i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Tipo Documento</label>
Traer de i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Numero Documento</label>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Nombre Completo</label>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Banco</label>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Tipo Cuenta</label>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Numero Cuenta</label>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                <label>Forma de Pago</label>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +                Anexos
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +        <h4 class="modal-title" id="adjuntarArchivoModal">Adjuntar Archivo</h4>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +        <button type="button" class="btn btn-outline-secondary" (click)="modal.dismiss('Cross click')">Cancelar</button>
Traer mediante i18n

2022-06-05 04:49 UTC, AlexFBP commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.html
> +        <button type="button" class="btn btn-danger" (click)="modal.close(true)">Aceptar</button>
Traer mediante i18n

2022-06-05 07:40 UTC, diagutierrezro reviewed
Todos los comentarios respecto a los textos de i18n los dejé abiertos para tenerlos presente, estos textos los ajusto al final cuando termine la parte de ordenes de devolución, los comentarios para quitar los onInit que no se usaban los cerré ya que los onInit ya los implementé

2022-06-05 07:40 UTC, diagutierrezro commented on src/app/pages/ordenesdevolucion/components/set-datosbeneficiario/set-datosbeneficiario.component.ts
> +import { getFilaSeleccionada, selectDocumentos, selectDocumentosDescarga } from '../../../../shared/selectors/shared.selectors';
En el siguiente commit agrego mas imports por lo que solo lo dejo en dos lineas

2022-06-05 07:40 UTC, diagutierrezro commented on src/app/pages/ordenesdevolucion/components/show-resumenordendevolucion/show-resumenordendevolucion.component.html
> +<p>show-resumenordendevolucion works!</p>
Es la creación inicial del formulario, posteriormente tendrá un validador pero por el momento (por facilidad mientras desarrollo) lo dejo así

2022-06-05 07:40 UTC, diagutierrezro commented on src/app/pages/ordenesdevolucion/components/show-resumenordendevolucion/show-resumenordendevolucion.component.ts
> +
Estaba así mientras desarrollaba esa parte, ya se encuentra implementado bien

2022-06-09 05:13 UTC, AlexFBP requested changes
En general, bien

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/components/show-resumenrelaciondevoluciones/show-resumenrelaciondevoluciones.component.ts
> +  ngOnDestroy() {
```suggestion
  }

  ngOnDestroy() {
```

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/components/stepper-ordenesdevolucion/stepper-relaciondevoluciones.component.html
> +                CREAR ORDEN DE DEVOLUCIÓN
Traer de i18n

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/components/stepper-ordenesdevolucion/stepper-relaciondevoluciones.component.html
> +                    <ng-template matStepLabel>Relación Devoluciones</ng-template>
Traer de i18n

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/components/stepper-ordenesdevolucion/stepper-relaciondevoluciones.component.html
> +                    <ng-template matStepLabel>Guardar</ng-template>
Traer de i18n

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/components/stepper-ordenesdevolucion/stepper-relaciondevoluciones.component.ts
> +    private fb: FormBuilder
```suggestion
    private fb: FormBuilder,
```

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/components/table-relaciondevoluciones/table-relaciondevoluciones.component.ts
> +   }
```suggestion
  }

```

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/effects/relaciondevoluciones.effects.spec.ts
> +  // let actions$: Observable<any>;
```suggestion
```

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/effects/relaciondevoluciones.effects.ts
> +    private router: Router
```suggestion
    private router: Router,
```

2022-06-09 05:13 UTC, AlexFBP commented on src/app/pages/relaciondevoluciones/relaciondevoluciones-routing.module.ts
> +  exports: [RouterModule]
```suggestion
  exports: [RouterModule],
```

2022-06-09 23:23 UTC, AlexFBP approved these changes
Aprobado con un comentario menor

2022-06-09 23:23 UTC, AlexFBP commented on src/assets/i18n/es.json
> +    "crear_relacion": "CREAR RELACIÓN DE DEVOLUCIONES",
(En general)
Evitar usar mayusculas en los textos, sean o no de interfaz, y mas bien crear una clase CSS, puede ser a nivel global:
```css
.mayus {
  text-transform: uppercase;
}
```
- [MDN: text-transform](https://developer.mozilla.org/es/docs/Web/CSS/text-transform)

2022-06-09 23:24 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/central_cuentas_cliente/355)

2022-06-09 23:25 UTC, merged