Feature/relacionautorizacion/tablaseguridadsocial
udistrital/central_cuentas_cliente pull request #41
Opened 2020-12-10 17:37 UTC by dmarcela09

Para este caso #33 se crean los siguientes procesos:

- [ ] Se crea la interfaz para elegir entre una relacion de autorizacion nomina funcionarios o seguridad social.
![Menú](https://user-images.githubusercontent.com/26507343/101808064-d9bd9680-3ae3-11eb-9eee-724ad9e47106.png)

- [ ] Se reutiliza componente de la tabla.
![Nómina de Funcionarios](https://user-images.githubusercontent.com/26507343/101808131-f0fc8400-3ae3-11eb-9b0d-1cd2ca8b987a.png)
![Seguridad Social](https://user-images.githubusercontent.com/26507343/101808205-0b366200-3ae4-11eb-987c-3016649cecf8.png)

- [ ] Se agrega un stepper para continuar el proceso de los siguientes issues, la vista de informacion de relacion se habia creado en un issue anterior.
![Paso 1: Información de Relación](https://user-images.githubusercontent.com/26507343/101808292-2a34f400-3ae4-11eb-8f1a-59ba91864e42.png)

2020-12-10 17:42 UTC, dmarcela09 commented
La ruta para este proceso es http://localhost:4200/#/pages/relacionautorizaciones/elegir

2020-12-14 17:11 UTC, BOTOOM requested changes
se solicita respuesta a una duda

2020-12-14 17:11 UTC, BOTOOM commented on src/app/pages/relacionautorizaciones/components/set-infonuevarelacion/set-infonuevarelacion.component.html
> +                    ***Autorízase al Pagador, para pagar con cargo al presupuesto de la vigencia 2020 y al PAC del mes correspondiente, la nómina de la entidad UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE
hay y un service que creaste en el cual esta el texto que aqui esta escrito para el caso de nomina y seguridad social, queria saber si eso lo ajustes en el otro pull o no, en caso que no este ajustado en el otro pull avísame por que debes ajustarlo

2020-12-14 17:21 UTC, dmarcela09 commented on src/app/pages/relacionautorizaciones/components/set-infonuevarelacion/set-infonuevarelacion.component.html
> +                    ***Autorízase al Pagador, para pagar con cargo al presupuesto de la vigencia 2020 y al PAC del mes correspondiente, la nómina de la entidad UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE
Si, alli ya esta ajustado, solo que revisandolo para verificar, lo deje como comentario

2020-12-14 22:01 UTC, BOTOOM approved these changes

2020-12-14 22:01 UTC, merged